plugins {
    id 'com.android.library'
    alias(libs.plugins.jetbrains.kotlin.android)
    id "org.jetbrains.kotlin.plugin.serialization" version "1.9.10"
    id "maven-publish"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId "com.basistheory"
            artifactId "android-threeds"
            version = project.hasProperty('version') ? project.version : 'default-version'
            artifact("$buildDir/outputs/aar/lib-release.aar")
        }

    }

    repositories {
        maven {
            name "GithubPackages"
            url uri("https://maven.pkg.github.com/basis-theory/android-threeds")

            credentials {
                username = "platform@basistheory.com"
                password = properties["GITHUB_TOKEN"] ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

android {
    namespace 'com.basistheory.threeds'
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            debuggable true
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        disable "NullSafeMutableLiveData"
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

configurations.all {
    resolutionStrategy {
        force 'io.netty:netty-codec-http2:4.1.135.Final'
        force 'io.netty:netty-handler:4.1.135.Final'
        force 'io.opentelemetry:opentelemetry-api:1.62.0'
        force 'com.google.protobuf:protobuf-java:3.25.5'
        force 'com.google.protobuf:protobuf-javalite:4.28.2'
        force 'com.nimbusds:nimbus-jose-jwt:9.37.2'
        force 'net.minidev:json-smart:2.5.2'
        force 'org.bouncycastle:bcpg-jdk18on:1.84'
        force 'org.bouncycastle:bcpkix-jdk18on:1.84'
        force 'org.bouncycastle:bcprov-jdk18on:1.84'
        force 'org.bouncycastle:bcprov-jdk15to18:1.84'
    }
}

dependencies {
    implementation "com.ravelin.threeds2service:threeds2service-sdk:2.0.2"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    implementation libs.androidx.core.ktx

    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.1"

}